### ISSUE TITLE
[建议]限制设备播放音乐

### ISSUE THREAD

**Issue by q629988171** [JumpAlang/Jusic-serve#3]
这个云点歌非常好，好像去到KTV一样，每个人都可以开个房间，进去听歌。

只有管理员才能播放歌曲，或指定用户播放歌曲，其他用户无法播放歌曲，也无法控制播放进度，确保始终只有一个设备在播放音乐。其他功能不受影响。

使用场景：用餐区（饭店，酒店，KFC，奶茶店，学校食堂，超市，公司，公共区域），大家听同一首歌。目前的听歌方式，无法应用于公共区域，每个人把手机拿出来都在放这首歌曲，播放进度有差异，那声音无法忍受。

**Comment by JumpAlang** [comment]
意见很好，
关于：
> 只有管理员才能播放歌曲，或指定用户播放歌曲，其他用户无法播放歌曲，也无法控制播放进度，确保始终只有一个设备在播放音乐。其他功能不受影响。
目前房间管理员有权限限制点歌及切歌。但是有个bug就是限制了管理员也不能点歌（后面会修复）。关于指定用户这个观点很好，后续会更新上去。同步听歌目前是不支持控制播放进度。

关于：
> 目前的听歌方式，无法应用于公共区域，每个人把手机拿出来都在放这首歌曲，播放进度有差异，那声音无法忍受。
这个确实无法避免
